piVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-consumer
  name: udaconnect-consumer
spec:
  ports:
  - name: "udaconnect-consumer"
    port: 9092
    targetPort: 9092
    nodePort: 300002
  selector:
    service: udaconnect-consumer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-consumer
  name: udaconnect-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-consumer
  template:
    metadata:
      labels:
        service: udaconnect-consumer
    spec:
      containers:
      - image: srimant/udaconnect-consumer:latest
        name: udaconnect-consumer
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always