openapi: 3.0.0
servers:
  - url: http://localhost:30001
    description: ''
    variables: {}
info:
  version: 82ba6f86-4edd-4e5c-90f0-6a1188e3ce12
  title: Udaconnect
  description: ''
  termsOfService: ''
  contact: {}
  license:
    name: ''
paths:
  /health:
    get:
      summary: check API Health status
      operationId: checkAPIHealthstatus
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
  /api/persons:
    get:
      summary: Get Persons
      operationId: GetPersons
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
    post:
      summary: POST Person
      operationId: POSTPerson
      parameters:
        - $ref: '#/components/parameters/Content-Type'
      responses:
        '200':
          description: ''
          headers: {}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              example:
                id: '6'
                first_name: veselin
                last_name: tonev
                company_name: Tonev
            example: "{\r\n    \"id\": \"6\",\"first_name\":\"veselin\", \"last_name\":\"tonev\",\"company_name\":\"Tonev\"\r\n}\r\n"
  /api/persons/5:
    get:
      summary: Get Person with ID
      operationId: GetPersonwithID
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
components:
  parameters:
    Content-Type:
      name: Content-Type
      in: header
      required: true
      style: simple
      schema:
        type: string
        example: application/json
security: []
tags: []
externalDocs:
  url: ''
  description: ''
warnings: []
